[pytest]
testpaths = Test_Cases
python_files = test_*.py,*_test.py,*_tests.py,*_tests/*.py
python_classes = Test*
python_functions = test_*
filterwarnings =ignore::pytest.PytestUnknownMarkWarning
addopts = -s
markers =
    prac_<dynamic_name>: mark test as practice,
    client_<dynamic_name>: mark test as client,
    release: mark test as release,
    databaseTC: mark test as database,
    smoke: mark test as smoke,
    regression: mark test as regression,
    sanity: mark test as sanity,
    demo: mark test as demo,
    project_<dynamic_name>: mark test as ArchiveAndPurging,
    <dynamic_name>_Module: mark test as Module dynamic_name,
    <dynamic_name>: mark test as <dynamic_name>,
    regression_<dynamic_name>: mark test as regression_<dynamic_name>
