import os
import sys

def prevent_bytecode_files():
    """
    Set environment variable to prevent Python from generating bytecode (.pyc) files.
    This should be called early in the application initialization.
    
    NOTE: This function is no longer needed for manual imports as the project now uses
    sitecustomize.py to set this globally. This is kept for backwards compatibility.
    """
    os.environ["PYTHONDONTWRITEBYTECODE"] = "1"
    sys.dont_write_bytecode = True
    print("Python bytecode generation disabled")

def clean_existing_bytecode():
    """
    Remove existing .pyc files and __pycache__ directories.
    Call this to clean up previously generated bytecode files.
    """
    import os
    import shutil
    
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    
    # Walk through all directories in the project
    for dirpath, dirnames, filenames in os.walk(root_dir):
        # Remove __pycache__ directories
        if '__pycache__' in dirnames:
            cache_dir = os.path.join(dirpath, '__pycache__')
            print(f"Removing {cache_dir}")
            shutil.rmtree(cache_dir, ignore_errors=True)
            dirnames.remove('__pycache__')
        
        # Remove .pyc files
        for filename in filenames:
            if filename.endswith('.pyc'):
                pyc_file = os.path.join(dirpath, filename)
                print(f"Removing {pyc_file}")
                try:
                    os.remove(pyc_file)
                except Exception as e:
                    print(f"Error removing {pyc_file}: {e}")
